name: Release tagged build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up JDK 8
        uses: https://gitea.com/actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup the workspace
        run: ./gradlew setupCIWorkspace

      - name: Publish to Maven, Modrinth, and CurseForge
        run: ./gradlew publish
        env:
          MAVEN_DEPLOY_USER: ${{ secrets.MAVEN_DEPLOY_USER }}
          MAVEN_DEPLOY_PASSWORD: ${{ secrets.MAVEN_DEPLOY_PASSWORD }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}

      - name: Release under current tag
        uses: actions/forgejo-release@v1
        with:
          direction: upload
          release-dir: build/libs
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ env.RELEASE_VERSION }}"
